# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dsn_cpp <- function(x, xi, omega, alpha, log_d) {
    .Call(`_snCpp_dsn_cpp`, x, xi, omega, alpha, log_d)
}

psn_cpp <- function(x, xi, omega, alpha, lower_tail, log_p) {
    .Call(`_snCpp_psn_cpp`, x, xi, omega, alpha, lower_tail, log_p)
}

qsn_cpp <- function(p, xi, omega, alpha, tau, tol) {
    .Call(`_snCpp_qsn_cpp`, p, xi, omega, alpha, tau, tol)
}

rsn_cpp <- function(n, xi, omega, alpha, tau) {
    .Call(`_snCpp_rsn_cpp`, n, xi, omega, alpha, tau)
}

dst_cpp <- function(x, xi, omega, alpha, nu, log_d) {
    .Call(`_snCpp_dst_cpp`, x, xi, omega, alpha, nu, log_d)
}

pst_cpp <- function(x, xi, omega, alpha, nu, method, lower_tail, log_p) {
    .Call(`_snCpp_pst_cpp`, x, xi, omega, alpha, nu, method, lower_tail, log_p)
}

qst_cpp <- function(p, xi, omega, alpha, nu, tol, method) {
    .Call(`_snCpp_qst_cpp`, p, xi, omega, alpha, nu, tol, method)
}

rst_cpp <- function(n, xi, omega, alpha, nu) {
    .Call(`_snCpp_rst_cpp`, n, xi, omega, alpha, nu)
}

owens_T <- function(h, a) {
    .Call(`_snCpp_owens_T`, h, a)
}

