# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
dsn_cpp <- function(x, xi = 0, omega = 1, alpha = 0, log_d = FALSE) {
    .Call(`_snCpp_dsn_cpp`, x, xi, omega, alpha, log_d)
}

#' @export
psn_cpp <- function(x, xi = 0, omega = 1, alpha = 0, lower_tail = TRUE, log_p = FALSE) {
    .Call(`_snCpp_psn_cpp`, x, xi, omega, alpha, lower_tail, log_p)
}

#' @export
qsn_cpp <- function(p, xi = 0, omega = 1, alpha = 0, tau = 0, tol = 1e-8) {
    .Call(`_snCpp_qsn_cpp`, p, xi, omega, alpha, tau, tol)
}

#' @export
rsn_cpp <- function(n, xi = 0, omega = 1, alpha = 0, tau = 0) {
    .Call(`_snCpp_rsn_cpp`, n, xi, omega, alpha, tau)
}

#' @export
dst_cpp <- function(x, xi = 0, omega = 1, alpha = 0, nu, log_d = FALSE) {
    .Call(`_snCpp_dst_cpp`, x, xi, omega, alpha, nu, log_d)
}

#' @export
pst_cpp <- function(x, xi = 0, omega = 1, alpha = 0, nu, method = 0L, lower_tail = TRUE, log_p = FALSE) {
    .Call(`_snCpp_pst_cpp`, x, xi, omega, alpha, nu, method, lower_tail, log_p)
}

#' @export
qst_cpp <- function(p, xi = 0, omega = 1, alpha = 0, nu, tol = 1e-8, method = 0L) {
    .Call(`_snCpp_qst_cpp`, p, xi, omega, alpha, nu, tol, method)
}

#' @export
rst_cpp <- function(n, xi = 0, omega = 1, alpha = 0, nu) {
    .Call(`_snCpp_rst_cpp`, n, xi, omega, alpha, nu)
}

#' @export
owens_T <- function(h, a) {
    .Call(`_snCpp_owens_T`, h, a)
}

